//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 12:35:25 AM CET 
//

package XMLMessages;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import GenericCommonClasses.IMessage;
import GenericCommonClasses.Parser;
import GenericCommonClasses.Parser.MessageType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorDetails">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="UnknownSender"/>
 *               &lt;enumeration value="InvalidOperation"/>
 *               &lt;enumeration value="TimeoutExceeded"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "errorDetails" })
@XmlRootElement(name = "Error")
public class Error implements IMessage
{

	@XmlElement(name = "ErrorDetails", required = true)
	protected String errorDetails;

	/**
	 * Gets the value of the errorDetails property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getErrorDetails()
	{
		return errorDetails;
	}

	/**
	 * Sets the value of the errorDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setErrorDetails(String value)
	{
		this.errorDetails = value;
	}

	@Override
	public String getString() throws JAXBException
	{
		return Parser.marshallMessage(this, Error.class);
	}

	@Override
	public MessageType getMessageType()
	{
		return MessageType.ERROR;
	}

}
