//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 12:16:20 AM CET 
//

package XMLMessages;

import java.io.IOException;
import java.math.BigInteger;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import GenericCommonClasses.AbstractMessage;
import GenericCommonClasses.GenericProtocol;
import GenericCommonClasses.IMessage;
import GenericCommonClasses.IServerProtocol;
import GenericCommonClasses.Parser;
import GenericCommonClasses.Parser.MessageType;
import XMLMessages.Solutiones.Solutions.Solution;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProblemType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="CommonData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="Solutions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Solution" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TaskId" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="TimeoutOccured" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="Type">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="Ongoing"/>
 *                                   &lt;enumeration value="Partial"/>
 *                                   &lt;enumeration value="Final"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ComputationsTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "problemType", "id", "commonData",
		"solutions" })
@XmlRootElement(name = "Solutions")
public class Solutiones extends AbstractMessage
{

	@XmlElement(name = "ProblemType", required = true)
	protected String problemType;
	@XmlElement(name = "Id", required = true)
	@XmlSchemaType(name = "unsignedLong")
	protected BigInteger id;
	@XmlElement(name = "CommonData")
	protected byte[] commonData;
	@XmlElement(name = "Solutions", required = true)
	protected Solutiones.Solutions solutions;

	/**
	 * <p>
	 * Creates an empty message.
	 * </p>
	 */
	public Solutiones()
	{
	}

	/**
	 * <p>
	 * Creates fully initialized message.
	 * </p>
	 * 
	 * @param problemType
	 * @param id
	 * @param commonData
	 * @param solutions
	 */
	public Solutiones(String problemType, BigInteger id, byte[] commonData,
			Solutions solutions)
	{
		super();
		this.problemType = problemType;
		this.id = id;
		this.commonData = commonData;
		this.solutions = solutions;
	}

	/**
	 * Gets the value of the problemType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProblemType()
	{
		return problemType;
	}

	/**
	 * Sets the value of the problemType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProblemType(String value)
	{
		this.problemType = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setId(BigInteger value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the commonData property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getCommonData()
	{
		return commonData;
	}

	/**
	 * Sets the value of the commonData property.
	 * 
	 * @param value
	 *            allowed object is byte[]
	 */
	public void setCommonData(byte[] value)
	{
		this.commonData = value;
	}

	/**
	 * Gets the value of the solutions property.
	 * 
	 * @return possible object is {@link Solutiones.Solutions }
	 * 
	 */
	public Solutiones.Solutions getSolutions()
	{
		return solutions;
	}

	/**
	 * Sets the value of the solutions property.
	 * 
	 * @param value
	 *            allowed object is {@link Solutiones.Solutions }
	 * 
	 */
	public void setSolutions(Solutiones.Solutions value)
	{
		this.solutions = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Solution" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="TaskId" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
	 *                   &lt;element name="TimeoutOccured" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
	 *                   &lt;element name="Type">
	 *                     &lt;simpleType>
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *                         &lt;enumeration value="Ongoing"/>
	 *                         &lt;enumeration value="Partial"/>
	 *                         &lt;enumeration value="Final"/>
	 *                       &lt;/restriction>
	 *                     &lt;/simpleType>
	 *                   &lt;/element>
	 *                   &lt;element name="ComputationsTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
	 *                   &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "solution" })
	public static class Solutions
	{

		@XmlElement(name = "Solution", required = true)
		protected List<Solutiones.Solutions.Solution> solution;

		/**
		 * Gets the value of the solution property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the solution property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSolution().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Solutiones.Solutions.Solution }
		 * 
		 * 
		 */
		public List<Solutiones.Solutions.Solution> getSolution()
		{
			if (solution == null)
			{
				solution = new ArrayList<Solutiones.Solutions.Solution>();
			}
			return this.solution;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="TaskId" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
		 *         &lt;element name="TimeoutOccured" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
		 *         &lt;element name="Type">
		 *           &lt;simpleType>
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
		 *               &lt;enumeration value="Ongoing"/>
		 *               &lt;enumeration value="Partial"/>
		 *               &lt;enumeration value="Final"/>
		 *             &lt;/restriction>
		 *           &lt;/simpleType>
		 *         &lt;/element>
		 *         &lt;element name="ComputationsTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
		 *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "taskId", "timeoutOccured", "type",
				"computationsTime", "data" })
		public static class Solution
		{

			@XmlElement(name = "TaskId")
			@XmlSchemaType(name = "unsignedLong")
			protected BigInteger taskId;
			@XmlElement(name = "TimeoutOccured")
			protected boolean timeoutOccured;
			@XmlElement(name = "Type", required = true)
			protected String type;
			@XmlElement(name = "ComputationsTime", required = true)
			@XmlSchemaType(name = "unsignedLong")
			protected BigInteger computationsTime;
			@XmlElement(name = "Data")
			protected byte[] data;

			/**
			 * Gets the value of the taskId property.
			 * 
			 * @return possible object is {@link BigInteger }
			 * 
			 */
			public BigInteger getTaskId()
			{
				return taskId;
			}

			/**
			 * Sets the value of the taskId property.
			 * 
			 * @param value
			 *            allowed object is {@link BigInteger }
			 * 
			 */
			public void setTaskId(BigInteger value)
			{
				this.taskId = value;
			}

			/**
			 * Gets the value of the timeoutOccured property.
			 * 
			 */
			public boolean isTimeoutOccured()
			{
				return timeoutOccured;
			}

			/**
			 * Sets the value of the timeoutOccured property.
			 * 
			 */
			public void setTimeoutOccured(boolean value)
			{
				this.timeoutOccured = value;
			}

			/**
			 * Gets the value of the type property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getType()
			{
				return type;
			}

			/**
			 * Sets the value of the type property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setType(String value)
			{
				this.type = value;
			}

			/**
			 * Gets the value of the computationsTime property.
			 * 
			 * @return possible object is {@link BigInteger }
			 * 
			 */
			public BigInteger getComputationsTime()
			{
				return computationsTime;
			}

			/**
			 * Sets the value of the computationsTime property.
			 * 
			 * @param value
			 *            allowed object is {@link BigInteger }
			 * 
			 */
			public void setComputationsTime(BigInteger value)
			{
				this.computationsTime = value;
			}

			/**
			 * Gets the value of the data property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getData()
			{
				return data;
			}

			/**
			 * Sets the value of the data property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setData(byte[] value)
			{
				this.data = value;
			}

		}

	}

	@Override
	public String getString() throws JAXBException
	{
		return Parser.marshallMessage(this, Solutiones.class);
	}

	@Override
	public MessageType getMessageType()
	{
		return MessageType.SOLUTION;
	}

	@Override
	public BigInteger getProblemId()
	{
		return getId();
	}

	@Override
	protected void getMessageResponse(IServerProtocol serverProtocol,
			Socket socket, List<IMessage> delayedResponse) throws IOException
	{
		List<Solution> solutionsToMerge = null;

		for (Solution s : getSolutions().getSolution())
			solutionsToMerge = serverProtocol
					.informAboutProblemSolution(getId(), getSolutions()
							.getSolution().get(0).getTaskId(), s);

		// Received all partial solutions?
		// so prepare them for merging
		if (solutionsToMerge != null)
		{
			Solutions solution = new Solutions();
			solution.getSolution().addAll(solutionsToMerge);
			delayedResponse.add(new Solutiones(getProblemType(), getId(),
					getCommonData(), solution));
		}

		// Relay information with BS
		serverProtocol.addBackupServerMessage(this);

		GenericProtocol.sendMessages(socket,
				serverProtocol.getNoOperationMessage());
	}
}